// Mocks generated by Mockito 5.4.2 from annotations
// in kiwit/test/mocks/auth/mock_remote_auth_datasource.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:kiwit/features/auth/data/datasources/remote/remote_auth_datasource.dart'
    as _i3;
import 'package:kiwit/features/auth/data/models/auth_model.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:retrofit/retrofit.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHttpResponse_0<T> extends _i1.SmartFake
    implements _i2.HttpResponse<T> {
  _FakeHttpResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RemoteAuthDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteAuthDataSource extends _i1.Mock
    implements _i3.RemoteAuthDataSource {
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> signIn(
          {required _i5.AuthModel? body}) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [],
          {#body: body},
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #signIn,
            [],
            {#body: body},
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #signIn,
            [],
            {#body: body},
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> signUp(
          {required _i5.AuthModel? body}) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [],
          {#body: body},
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #signUp,
            [],
            {#body: body},
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #signUp,
            [],
            {#body: body},
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> signOut(
          {required String? accessToken}) =>
      (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
          {#accessToken: accessToken},
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #signOut,
            [],
            {#accessToken: accessToken},
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #signOut,
            [],
            {#accessToken: accessToken},
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> deleteAccount(
          {required String? accessToken}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [],
          {#accessToken: accessToken},
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #deleteAccount,
            [],
            {#accessToken: accessToken},
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #deleteAccount,
            [],
            {#accessToken: accessToken},
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
}
